# Generated by Django 4.0.2 on 2022-02-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleprogress',
            name='completion_status',
        ),
        migrations.RemoveField(
            model_name='moduleprogress',
            name='module_id',
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='module_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
