# Generated by Django 4.0.2 on 2022-02-27 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='investment_category',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='investment_text',
        ),
        migrations.AddField(
            model_name='investment',
            name='amount_invested',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='current_investment_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
