# Generated by Django 4.0.2 on 2022-02-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_investment_investment_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_study_title', models.CharField(max_length=100)),
                ('case_study_investment_name', models.CharField(max_length=100)),
                ('case_study_content', models.TextField()),
                ('case_study_value', models.IntegerField()),
            ],
        ),
    ]
