# Generated by Django 4.0.2 on 2022-02-27 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_course_id_moduleprogress_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleprogress',
            name='course_name',
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
            preserve_default=False,
        ),
    ]
