# Generated by Django 4.0.2 on 2022-02-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_moduleprog_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleprog',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
