# Generated by Django 4.0.2 on 2022-02-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_moduleprog_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='completion_status',
        ),
        migrations.RemoveField(
            model_name='question',
            name='module_id',
        ),
        migrations.AddField(
            model_name='question',
            name='option_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
