# Generated by Django 4.0.2 on 2022-02-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_casestudies'),
        ('app', '0010_remove_question_completion_status_and_more'),
    ]

    operations = [
    ]
